---
functional:
  - Пользователь должен иметь возможность войти на сайт, используя имя пользователя и пароль
  - Пользователь должен иметь возможность выйти из своего профиля
  - Пользователь должен иметь возможность входа через социальные сети
  - Пользователь должен иметь возможность работы с личным кабинетом
  - Пользователь должен иметь возможность восстановить свой пароль при утере данных
  - Пользователь должен иметь возможность сменить язык 
  - Пользователь должен иметь возможность взаимодействия с другими пользователями
  - Пользователь должен иметь возможность создать игру по своим параметрам
  - Пользователь должен иметь возможность выбора игры с ботом или реальным игроком
  - Сайт должен создавать профили пользователей
  - Сайт должен добавлять, изменять и удалять текстовый и мультимедийный контент
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность просмотра рейтинга других игроков
  - У сайта должен быть сбор обратной связи через контактные формы или электронную почту
  - Пользователь должен иметь возможность просмотра истории сыгранных игр
  - Пользователь должен иметь возможность просмотра статистики своих игр
  - Пользователь должен иметь возможность просмотра статистики игр других участников
  - Пользователь должен иметь возможность просмотра общего рейтинга всех игроков
  - Пользователь должен иметь возможность просмотра списка задач в играх
  - Пользователь должен иметь возможность просмотра турниров

