---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
   - Пользователь должен иметь возможность авторизации на сайте
  - Пользователь должен иметь возможность выйти из своего профиля
  - Пользователь должен иметь возможность входа через социальные сети
  - Пользователь должен иметь возможность восстановить свой пароль при утере данных
  - Пользователь должен иметь доступ в "My Profile"
  - Пользователь должен иметь доступ в "Settings"
  - Пользователь должен иметь доступ в "Users Rating"
  - Пользователь должен иметь доступ в "Tasks"
  - Пользователь должен иметь доступ в "Tournaments"
  - Пользователь должен иметь доступ в "SourceCode"
  - Пользователь должен иметь доступ в "Hexlet"
  - Пользователя должно перенаправлять на корпоративный Discord по нажатию на кнопку "Join Discord" 
  - Пользователя должно перенаправлять на Telegram канал по нажатию на кнопку "Tg#codebattle"
  - Пользователь должен иметь возможность отправить сообщение в общем чате
  - Пользователь должен иметь возможность отправить личное сообщение другому игроку
  - Пользователь должен иметь возможность отправить приглашение на спарринг с другим игроком 
  - Пользователь должен иметь возможность создать игру по своим параметрам
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность просмотра таблицы лидеров за определенное время
  - Пользователь должен иметь возможность просмотра истории сыгранных игр
  - Пользователь должен иметь возможность просмотра статистики своих игр
  - Пользователь должен иметь возможность просмотра таблицы завершенных игр
  - Пользователь должен иметь возможность просмотра статистики игр других участников
  - Пользователь должен иметь возможность изменить свой никнейм в настройках
  - Пользователь должен иметь возможность изменить язык программирования в настройках
  - Пользователь должен иметь возможность дать название своему клану на странице Settings
  - Пользователь должен иметь возможность выбрать музыку для игры на странице Settings
  - Пользователь должен иметь возможность установить уровень громкости музыки на странице Settings
  - Пользователь должен иметь возможность поиска игрока на странице Users rating
  - Пользователь должен иметь возможность установить на странице Users rating количество игроков в рейтинге
  - Пользователь должен иметь возможность сортировать игроков на странице Users rating в рейтинге по времени
  - Пользователь должен иметь возможность при сортировке игроков на странице Users rating установить галочку  With bots
  - Пользователь должен иметь возможность просмотра списка задач в играх на странице “Tasks”
  - Пользователь должен иметь возможность создать новую задачу на странице “Tasks”
  - Пользователь должен иметь возможность просмотра записи турниров на странице “Tournaments”
  - Пользователь должен иметь возможность вернуться обратно на страницу “Tournaments” после просмотра турнира
  - Пользователь должен иметь возможность просмотра количества игроков он-лайн 



