---
functional:
  - Пользователь должен иметь возможность войти в систему, используя имя пользователя и пароль
  - Пользователь должен иметь возможность входа через социальные сети
  - Пользователь должен иметь возможность работы с личным кабинетом
  - Пользователь должен иметь возможность восстановить свой пароль при утере данных
  - Пользователь должен иметь возможность сменить язык 
  - Пользователь должен иметь возможность взаимодействия с другими пользователями
  - Сайт должен создавать профили пользователей
  - Сайт должен добавлять, изменять и удалять текстовый и мультимедийный контент
  - 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность просмотра рейтинга других игроков
  - Сбор обратной связи через контактные формы или электронную почту
