---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизации на сайте
  - Пользователь должен иметь возможность выйти из своего профиля
  - Пользователь должен иметь возможность входа через социальные сети
  - Пользователь должен иметь возможность восстановить свой пароль
  - Пользователь должен иметь доступ в "My Profile"
  - Пользователь должен иметь доступ в "Settings"
  - Пользователь должен иметь доступ в "Users Rating"
  - Пользователь должен иметь доступ в "Tasks"
  - Пользователь должен иметь доступ в "Tournaments"
  - Пользователь должен иметь доступ в "SourceCode"
  - Пользователь должен иметь доступ в "Hexlet"
  - Пользователя должно перенаправлять на корпоративный Discord по нажатию на кнопку "Join Discord" 
  - Пользователя должно перенаправлять на Telegram канал по нажатию на кнопку "Tg#codebattle"
  - Пользователь должен иметь возможность отправить сообщение в общем чате
  - Пользователь должен иметь возможность отправить личное сообщение другому игроку
  - Пользователь должен иметь возможность отправить приглашение на спарринг с другим игроком 
  - Пользователь должен иметь возможность видеть приглашения на спарринг от других игроков
  - Пользователь должен иметь возможность скопировать имя другого игрока в чате
  - Пользователь должен иметь возможность просмотреть профиль другого игрока
  - Пользователь должен иметь возможность следить за действиями другого игрока
  - Пользователь должен иметь возможность прекратить отслеживание действий другого игрока
  - Пользователь должен иметь возможность создать игру по своим параметрам
  - Пользователь должен иметь возможность изменить язык программирования на странице Games
  - Пользователь должен иметь возможность выбрать цветовую схему на странице Games
  - Пользователь должен иметь возможность написать код решения задачи в поле на вкладке “Editor”
  - Пользователь должен иметь возможность запустить написанный код по задаче на странице Games 
  - Пользователь должен иметь возможность просмотра результата тестов или ошибки компиляции после проверки кода
  - Пользователь должен иметь возможность сбросить решение задачи на странице Games
  - Пользователь должен иметь возможность покинуть игру/сдаться на странице Games
  - Пользователь должен иметь возможность получить уведомление о результате в конце игры
  - Пользователь должен иметь возможность перейти в свой профиль со страницы Games
  - Пользователь должен иметь возможность изменить язык на странице Games
  - Пользователь должен иметь возможность написать в чат на странице Games
  - Пользователь должен иметь возможность просмотреть историю чата на странице Games
  - Пользователь должен иметь возможность вернуться на главную страницу сайта со страницы Games
  - Пользователь должен иметь возможность открыть описание задачи на странице Games в отдельном окне
  - Пользователь должен иметь возможность изменить язык в отдельном окне описания задачи на странице Games
  - Пользователь должен иметь возможность закрыть всплывающее окно описания задачи с помощью элемента управления в форме знака Х на странице Games
  - Пользователь должен иметь возможность закрыть всплывающее окно описания задачи с помощью кнопки “x Close” на странице Games
  - Пользователь должен иметь возможность открыть гид по игре на странице Games
  - Пользователь должен иметь возможность просмотра подсказок гида с помощью модальных окон на странице Games
  - Пользователь должен иметь возможность вернуться к просмотру предыдущему модальному окну с подсказкой гида на странице Games
  - Пользователь должен иметь возможность закрыть модальное окно с подсказкой гида на странице Games
  - Пользователь должен иметь возможность просмотра отведенного времени на игру на странице Games
  - Пользователь должен иметь возможность просмотреть решение оппонента на странице Games
  - Пользователь должен иметь возможность провести повторный матч с тем же оппонентом на странице Games

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Пользователь должен иметь возможность просмотра таблицы лидеров за определенное время
  - Пользователь должен иметь возможность просмотра истории сыгранных игр
  - Пользователь должен иметь возможность просмотра статистики своих игр
  - Пользователь должен иметь возможность просмотра данных по своим завершенным играм
  - Пользователь должен иметь возможность просмотра статистики игр других участников
  - Пользователь должен иметь возможность просмотра количества игроков он-лайн
  - Пользователь должен иметь возможность изменить свой никнейм в настройках
  - Пользователь должен иметь возможность изменить язык программирования в настройках
  - Пользователь должен иметь возможность дать название своему клану на странице Settings
  - Пользователь должен иметь возможность выбрать музыку для игры на странице Settings
  - Пользователь должен иметь возможность установить уровень громкости музыки на странице Settings
  - Пользователь должен иметь возможность поиска игрока на странице Users rating
  - Пользователь должен иметь возможность установить на странице Users rating количество игроков в рейтинге
  - Пользователь должен иметь возможность сортировать игроков на странице Users rating в рейтинге по времени
  - Пользователь должен иметь возможность просмотра списка задач в играх на странице “Tasks”
  - Пользователь должен иметь возможность создать новую задачу на странице “Tasks”
  - Пользователь должен иметь возможность дать название новой задаче на странице “Create Tasks”
  - Пользователь должен иметь возможность добавить описание для новой задачи на странице “Create Tasks”
  - Пользователь должен иметь возможность выбрать уровень сложности новой задачи на странице “Create Tasks”
  - Пользователь должен иметь возможность выбрать на каком языке описывать задачу на странице “Create Tasks”
  - Пользователь должен иметь возможность установить кому будет доступна задача на странице “Create Tasks”
  - Пользователь должен иметь возможность установить типы входных параметров для новой задачи на странице “Create Tasks”
  - Пользователь должен иметь возможность установить тип выходного параметра для новой задачи на странице “Create Tasks”
  - Пользователь должен иметь возможность протестировать новую задачу на странице “Create Tasks”
  - Пользователь должен иметь возможность отследить статус заполнения все
  - Пользователь должен иметь возможность просмотра списка турниров на странице “Tournaments”
  - Пользователь должен иметь возможность просмотра данных о завершенных турнирах на странице “Tournaments”
  - Пользователь должен иметь возможность просмотра данных о предстоящих турнирах на странице “Tournaments”
  - Пользователь должен иметь возможность вернуться обратно на страницу “Tournaments” после просмотра данных о турнире
  - Пользователь должен иметь возможность принять участие в предстоящих турнирах на странице “Tournaments”
  - Пользователь должен иметь возможность отменить участие в предстоящих турнирах на странице “Tournaments”
  - Пользователь должен иметь возможность вернуться обратно на страницу “Tournaments” после просмотра данных о турнире





