---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность войти на сайт, используя имя пользователя и пароль
  - Пользователь должен иметь возможность выйти из своего профиля
  - Пользователь должен иметь возможность входа через социальные сети
  - Пользователь должен иметь возможность восстановить свой пароль при утере данных
  - Пользователь должен иметь доступ в "My Profile"
  - Пользователь должен иметь доступ в "Settings"
  - Пользователь должен иметь доступ в "Users Rating"
  - Пользователь должен иметь доступ в "Tasks"
  - Пользователь должен иметь доступ в "Tournaments"
  - Пользователь должен иметь доступ в "SourceCode"
  - Пользователь должен иметь доступ в "Hexlet"
  - Пользователя должно перенаправлять на корпоративный Discord по нажатию на кнопку "Join Discord" 
  - Пользователя должно перенаправлять на Telegram канал по нажатию на кнопку "Tg#codebattle"
  - Пользователь должен иметь возможность изменять "Settings"
  - Пользователь должен иметь возможность взаимодействия с другими пользователями
  - Пользователь должен иметь возможность создать игру по своим параметрам
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - У сайта должен быть сбор обратной связи через контактные формы или электронную почту
  - Пользователь должен иметь возможность просмотра истории сыгранных игр
  - Пользователь должен иметь возможность просмотра статистики своих игр
  - Пользователь должен иметь возможность просмотра статистики игр других участников
  - Пользователь должен иметь возможность просмотра списка задач в играх
  - Пользователь должен иметь возможность просмотра турниров

